// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: chat.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	Chatting(ctx context.Context, in *ProtoChatUserRequest, opts ...grpc.CallOption) (UserService_ChattingClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Chatting(ctx context.Context, in *ProtoChatUserRequest, opts ...grpc.CallOption) (UserService_ChattingClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], "/proto.UserService/Chatting", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceChattingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ChattingClient interface {
	Recv() (*ProtoChatUserReponse, error)
	grpc.ClientStream
}

type userServiceChattingClient struct {
	grpc.ClientStream
}

func (x *userServiceChattingClient) Recv() (*ProtoChatUserReponse, error) {
	m := new(ProtoChatUserReponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	Chatting(*ProtoChatUserRequest, UserService_ChattingServer) error
	//mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) Chatting(*ProtoChatUserRequest, UserService_ChattingServer) error {
	return status.Errorf(codes.Unimplemented, "method Chatting not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_Chatting_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProtoChatUserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).Chatting(m, &userServiceChattingServer{stream})
}

type UserService_ChattingServer interface {
	Send(*ProtoChatUserReponse) error
	grpc.ServerStream
}

type userServiceChattingServer struct {
	grpc.ServerStream
}

func (x *userServiceChattingServer) Send(m *ProtoChatUserReponse) error {
	return x.ServerStream.SendMsg(m)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chatting",
			Handler:       _UserService_Chatting_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}
